Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
#        show_sql: true
        format_sql: true
#  h2:
#    console:
#      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace